### PR TITLE
Fix 403 page

### PR DESCRIPTION
**Pull request by Klako**
Fixes the 403 page so it looks good instead of not good. #1 

To reproduce in a local environment:
1. Fire up docker and push this branch build to it.
2. Pick a random scoutid authenticated website you don't have access to.
3. Try to login and record the request to scoutid.se/simplesaml/saml2/idp/SSOService.php.
4. Copy the request url and change host to your local scoutid host.
5. It will now "emulate" a request to the website through your local scoutid.

### CODE REVIEW

**Comment by Klako** [comment]
No idea what information there should be except either static contact information to the scoutid group or to the website owner "Contact an administrator near you".

**Comment by Klako** [comment]
The text uses a couple of optional entries in the metadata.

First it checks for possible contacts by looking for a `contacts` element with the following format:
```
'contacts' => [
    [
        'contactType' => 'technical' | 'support' | 'administrative',
        'emailAddress' => 'contact@example.com',
    ],
    ...
],
```
It looks for the first match.

Secondly it looks for an `OrganizationURL` element which should be the website for the SP owner.

Lastly it just writes some generic text that tells the user to contact whoever is the owner of the SP.

**Comment by mrManner** [comment]
I'll do a test run after lunch, but from just looking at the commits it looks good! 👍

**Comment by Klako** [comment]
Changes will merge into master from #3 instead.

**Pull request closed without merging**
